// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: movie.proto

package com.example.proto;

public final class MovieProtos {
  private MovieProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MovieOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.Movie)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>required string id = 1;</code>
     */
    java.lang.String getId();
    /**
     * <code>required string id = 1;</code>
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>optional uint64 movieId = 2;</code>
     */
    boolean hasMovieId();
    /**
     * <code>optional uint64 movieId = 2;</code>
     */
    long getMovieId();

    /**
     * <code>optional string name = 3;</code>
     */
    boolean hasName();
    /**
     * <code>optional string name = 3;</code>
     */
    java.lang.String getName();
    /**
     * <code>optional string name = 3;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>optional string createdDate = 4;</code>
     */
    boolean hasCreatedDate();
    /**
     * <code>optional string createdDate = 4;</code>
     */
    java.lang.String getCreatedDate();
    /**
     * <code>optional string createdDate = 4;</code>
     */
    com.google.protobuf.ByteString
        getCreatedDateBytes();
  }
  /**
   * Protobuf type {@code proto.Movie}
   */
  public  static final class Movie extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.Movie)
      MovieOrBuilder {
    // Use Movie.newBuilder() to construct.
    private Movie(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Movie() {
      id_ = "";
      movieId_ = 0L;
      name_ = "";
      createdDate_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Movie(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              id_ = bs;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              movieId_ = input.readUInt64();
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              name_ = bs;
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              createdDate_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.proto.MovieProtos.internal_static_proto_Movie_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.proto.MovieProtos.internal_static_proto_Movie_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.proto.MovieProtos.Movie.class, com.example.proto.MovieProtos.Movie.Builder.class);
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object id_;
    /**
     * <code>required string id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string id = 1;</code>
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          id_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MOVIEID_FIELD_NUMBER = 2;
    private long movieId_;
    /**
     * <code>optional uint64 movieId = 2;</code>
     */
    public boolean hasMovieId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional uint64 movieId = 2;</code>
     */
    public long getMovieId() {
      return movieId_;
    }

    public static final int NAME_FIELD_NUMBER = 3;
    private volatile java.lang.Object name_;
    /**
     * <code>optional string name = 3;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string name = 3;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string name = 3;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CREATEDDATE_FIELD_NUMBER = 4;
    private volatile java.lang.Object createdDate_;
    /**
     * <code>optional string createdDate = 4;</code>
     */
    public boolean hasCreatedDate() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string createdDate = 4;</code>
     */
    public java.lang.String getCreatedDate() {
      java.lang.Object ref = createdDate_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          createdDate_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string createdDate = 4;</code>
     */
    public com.google.protobuf.ByteString
        getCreatedDateBytes() {
      java.lang.Object ref = createdDate_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        createdDate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt64(2, movieId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, name_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, createdDate_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, movieId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, name_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, createdDate_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.example.proto.MovieProtos.Movie)) {
        return super.equals(obj);
      }
      com.example.proto.MovieProtos.Movie other = (com.example.proto.MovieProtos.Movie) obj;

      boolean result = true;
      result = result && (hasId() == other.hasId());
      if (hasId()) {
        result = result && getId()
            .equals(other.getId());
      }
      result = result && (hasMovieId() == other.hasMovieId());
      if (hasMovieId()) {
        result = result && (getMovieId()
            == other.getMovieId());
      }
      result = result && (hasName() == other.hasName());
      if (hasName()) {
        result = result && getName()
            .equals(other.getName());
      }
      result = result && (hasCreatedDate() == other.hasCreatedDate());
      if (hasCreatedDate()) {
        result = result && getCreatedDate()
            .equals(other.getCreatedDate());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasId()) {
        hash = (37 * hash) + ID_FIELD_NUMBER;
        hash = (53 * hash) + getId().hashCode();
      }
      if (hasMovieId()) {
        hash = (37 * hash) + MOVIEID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getMovieId());
      }
      if (hasName()) {
        hash = (37 * hash) + NAME_FIELD_NUMBER;
        hash = (53 * hash) + getName().hashCode();
      }
      if (hasCreatedDate()) {
        hash = (37 * hash) + CREATEDDATE_FIELD_NUMBER;
        hash = (53 * hash) + getCreatedDate().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.example.proto.MovieProtos.Movie parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.proto.MovieProtos.Movie parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.proto.MovieProtos.Movie parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.proto.MovieProtos.Movie parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.proto.MovieProtos.Movie parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.proto.MovieProtos.Movie parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.proto.MovieProtos.Movie parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.example.proto.MovieProtos.Movie parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.proto.MovieProtos.Movie parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.proto.MovieProtos.Movie parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.example.proto.MovieProtos.Movie prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.Movie}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.Movie)
        com.example.proto.MovieProtos.MovieOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.example.proto.MovieProtos.internal_static_proto_Movie_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.example.proto.MovieProtos.internal_static_proto_Movie_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.example.proto.MovieProtos.Movie.class, com.example.proto.MovieProtos.Movie.Builder.class);
      }

      // Construct using com.example.proto.MovieProtos.Movie.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        id_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        movieId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        createdDate_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.example.proto.MovieProtos.internal_static_proto_Movie_descriptor;
      }

      public com.example.proto.MovieProtos.Movie getDefaultInstanceForType() {
        return com.example.proto.MovieProtos.Movie.getDefaultInstance();
      }

      public com.example.proto.MovieProtos.Movie build() {
        com.example.proto.MovieProtos.Movie result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.example.proto.MovieProtos.Movie buildPartial() {
        com.example.proto.MovieProtos.Movie result = new com.example.proto.MovieProtos.Movie(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.movieId_ = movieId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.createdDate_ = createdDate_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.example.proto.MovieProtos.Movie) {
          return mergeFrom((com.example.proto.MovieProtos.Movie)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.example.proto.MovieProtos.Movie other) {
        if (other == com.example.proto.MovieProtos.Movie.getDefaultInstance()) return this;
        if (other.hasId()) {
          bitField0_ |= 0x00000001;
          id_ = other.id_;
          onChanged();
        }
        if (other.hasMovieId()) {
          setMovieId(other.getMovieId());
        }
        if (other.hasName()) {
          bitField0_ |= 0x00000004;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasCreatedDate()) {
          bitField0_ |= 0x00000008;
          createdDate_ = other.createdDate_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasId()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.example.proto.MovieProtos.Movie parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.example.proto.MovieProtos.Movie) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object id_ = "";
      /**
       * <code>required string id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string id = 1;</code>
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            id_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string id = 1;</code>
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>required string id = 1;</code>
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }

      private long movieId_ ;
      /**
       * <code>optional uint64 movieId = 2;</code>
       */
      public boolean hasMovieId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional uint64 movieId = 2;</code>
       */
      public long getMovieId() {
        return movieId_;
      }
      /**
       * <code>optional uint64 movieId = 2;</code>
       */
      public Builder setMovieId(long value) {
        bitField0_ |= 0x00000002;
        movieId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 movieId = 2;</code>
       */
      public Builder clearMovieId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        movieId_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>optional string name = 3;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string name = 3;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string name = 3;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 3;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 3;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000004);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 3;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        name_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object createdDate_ = "";
      /**
       * <code>optional string createdDate = 4;</code>
       */
      public boolean hasCreatedDate() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string createdDate = 4;</code>
       */
      public java.lang.String getCreatedDate() {
        java.lang.Object ref = createdDate_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            createdDate_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string createdDate = 4;</code>
       */
      public com.google.protobuf.ByteString
          getCreatedDateBytes() {
        java.lang.Object ref = createdDate_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          createdDate_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string createdDate = 4;</code>
       */
      public Builder setCreatedDate(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        createdDate_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string createdDate = 4;</code>
       */
      public Builder clearCreatedDate() {
        bitField0_ = (bitField0_ & ~0x00000008);
        createdDate_ = getDefaultInstance().getCreatedDate();
        onChanged();
        return this;
      }
      /**
       * <code>optional string createdDate = 4;</code>
       */
      public Builder setCreatedDateBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        createdDate_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:proto.Movie)
    }

    // @@protoc_insertion_point(class_scope:proto.Movie)
    private static final com.example.proto.MovieProtos.Movie DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.example.proto.MovieProtos.Movie();
    }

    public static com.example.proto.MovieProtos.Movie getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Movie>
        PARSER = new com.google.protobuf.AbstractParser<Movie>() {
      public Movie parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Movie(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Movie> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Movie> getParserForType() {
      return PARSER;
    }

    public com.example.proto.MovieProtos.Movie getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MovieListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.MovieList)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .proto.Movie movie = 1;</code>
     */
    java.util.List<com.example.proto.MovieProtos.Movie> 
        getMovieList();
    /**
     * <code>repeated .proto.Movie movie = 1;</code>
     */
    com.example.proto.MovieProtos.Movie getMovie(int index);
    /**
     * <code>repeated .proto.Movie movie = 1;</code>
     */
    int getMovieCount();
    /**
     * <code>repeated .proto.Movie movie = 1;</code>
     */
    java.util.List<? extends com.example.proto.MovieProtos.MovieOrBuilder> 
        getMovieOrBuilderList();
    /**
     * <code>repeated .proto.Movie movie = 1;</code>
     */
    com.example.proto.MovieProtos.MovieOrBuilder getMovieOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code proto.MovieList}
   */
  public  static final class MovieList extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.MovieList)
      MovieListOrBuilder {
    // Use MovieList.newBuilder() to construct.
    private MovieList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MovieList() {
      movie_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MovieList(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                movie_ = new java.util.ArrayList<com.example.proto.MovieProtos.Movie>();
                mutable_bitField0_ |= 0x00000001;
              }
              movie_.add(
                  input.readMessage(com.example.proto.MovieProtos.Movie.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          movie_ = java.util.Collections.unmodifiableList(movie_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.proto.MovieProtos.internal_static_proto_MovieList_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.proto.MovieProtos.internal_static_proto_MovieList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.proto.MovieProtos.MovieList.class, com.example.proto.MovieProtos.MovieList.Builder.class);
    }

    public static final int MOVIE_FIELD_NUMBER = 1;
    private java.util.List<com.example.proto.MovieProtos.Movie> movie_;
    /**
     * <code>repeated .proto.Movie movie = 1;</code>
     */
    public java.util.List<com.example.proto.MovieProtos.Movie> getMovieList() {
      return movie_;
    }
    /**
     * <code>repeated .proto.Movie movie = 1;</code>
     */
    public java.util.List<? extends com.example.proto.MovieProtos.MovieOrBuilder> 
        getMovieOrBuilderList() {
      return movie_;
    }
    /**
     * <code>repeated .proto.Movie movie = 1;</code>
     */
    public int getMovieCount() {
      return movie_.size();
    }
    /**
     * <code>repeated .proto.Movie movie = 1;</code>
     */
    public com.example.proto.MovieProtos.Movie getMovie(int index) {
      return movie_.get(index);
    }
    /**
     * <code>repeated .proto.Movie movie = 1;</code>
     */
    public com.example.proto.MovieProtos.MovieOrBuilder getMovieOrBuilder(
        int index) {
      return movie_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      for (int i = 0; i < getMovieCount(); i++) {
        if (!getMovie(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < movie_.size(); i++) {
        output.writeMessage(1, movie_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < movie_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, movie_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.example.proto.MovieProtos.MovieList)) {
        return super.equals(obj);
      }
      com.example.proto.MovieProtos.MovieList other = (com.example.proto.MovieProtos.MovieList) obj;

      boolean result = true;
      result = result && getMovieList()
          .equals(other.getMovieList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (getMovieCount() > 0) {
        hash = (37 * hash) + MOVIE_FIELD_NUMBER;
        hash = (53 * hash) + getMovieList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.example.proto.MovieProtos.MovieList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.proto.MovieProtos.MovieList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.proto.MovieProtos.MovieList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.proto.MovieProtos.MovieList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.proto.MovieProtos.MovieList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.proto.MovieProtos.MovieList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.proto.MovieProtos.MovieList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.example.proto.MovieProtos.MovieList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.proto.MovieProtos.MovieList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.proto.MovieProtos.MovieList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.example.proto.MovieProtos.MovieList prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.MovieList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.MovieList)
        com.example.proto.MovieProtos.MovieListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.example.proto.MovieProtos.internal_static_proto_MovieList_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.example.proto.MovieProtos.internal_static_proto_MovieList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.example.proto.MovieProtos.MovieList.class, com.example.proto.MovieProtos.MovieList.Builder.class);
      }

      // Construct using com.example.proto.MovieProtos.MovieList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getMovieFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (movieBuilder_ == null) {
          movie_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          movieBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.example.proto.MovieProtos.internal_static_proto_MovieList_descriptor;
      }

      public com.example.proto.MovieProtos.MovieList getDefaultInstanceForType() {
        return com.example.proto.MovieProtos.MovieList.getDefaultInstance();
      }

      public com.example.proto.MovieProtos.MovieList build() {
        com.example.proto.MovieProtos.MovieList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.example.proto.MovieProtos.MovieList buildPartial() {
        com.example.proto.MovieProtos.MovieList result = new com.example.proto.MovieProtos.MovieList(this);
        int from_bitField0_ = bitField0_;
        if (movieBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            movie_ = java.util.Collections.unmodifiableList(movie_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.movie_ = movie_;
        } else {
          result.movie_ = movieBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.example.proto.MovieProtos.MovieList) {
          return mergeFrom((com.example.proto.MovieProtos.MovieList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.example.proto.MovieProtos.MovieList other) {
        if (other == com.example.proto.MovieProtos.MovieList.getDefaultInstance()) return this;
        if (movieBuilder_ == null) {
          if (!other.movie_.isEmpty()) {
            if (movie_.isEmpty()) {
              movie_ = other.movie_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureMovieIsMutable();
              movie_.addAll(other.movie_);
            }
            onChanged();
          }
        } else {
          if (!other.movie_.isEmpty()) {
            if (movieBuilder_.isEmpty()) {
              movieBuilder_.dispose();
              movieBuilder_ = null;
              movie_ = other.movie_;
              bitField0_ = (bitField0_ & ~0x00000001);
              movieBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getMovieFieldBuilder() : null;
            } else {
              movieBuilder_.addAllMessages(other.movie_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getMovieCount(); i++) {
          if (!getMovie(i).isInitialized()) {
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.example.proto.MovieProtos.MovieList parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.example.proto.MovieProtos.MovieList) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.example.proto.MovieProtos.Movie> movie_ =
        java.util.Collections.emptyList();
      private void ensureMovieIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          movie_ = new java.util.ArrayList<com.example.proto.MovieProtos.Movie>(movie_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.example.proto.MovieProtos.Movie, com.example.proto.MovieProtos.Movie.Builder, com.example.proto.MovieProtos.MovieOrBuilder> movieBuilder_;

      /**
       * <code>repeated .proto.Movie movie = 1;</code>
       */
      public java.util.List<com.example.proto.MovieProtos.Movie> getMovieList() {
        if (movieBuilder_ == null) {
          return java.util.Collections.unmodifiableList(movie_);
        } else {
          return movieBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .proto.Movie movie = 1;</code>
       */
      public int getMovieCount() {
        if (movieBuilder_ == null) {
          return movie_.size();
        } else {
          return movieBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .proto.Movie movie = 1;</code>
       */
      public com.example.proto.MovieProtos.Movie getMovie(int index) {
        if (movieBuilder_ == null) {
          return movie_.get(index);
        } else {
          return movieBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .proto.Movie movie = 1;</code>
       */
      public Builder setMovie(
          int index, com.example.proto.MovieProtos.Movie value) {
        if (movieBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMovieIsMutable();
          movie_.set(index, value);
          onChanged();
        } else {
          movieBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .proto.Movie movie = 1;</code>
       */
      public Builder setMovie(
          int index, com.example.proto.MovieProtos.Movie.Builder builderForValue) {
        if (movieBuilder_ == null) {
          ensureMovieIsMutable();
          movie_.set(index, builderForValue.build());
          onChanged();
        } else {
          movieBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto.Movie movie = 1;</code>
       */
      public Builder addMovie(com.example.proto.MovieProtos.Movie value) {
        if (movieBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMovieIsMutable();
          movie_.add(value);
          onChanged();
        } else {
          movieBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .proto.Movie movie = 1;</code>
       */
      public Builder addMovie(
          int index, com.example.proto.MovieProtos.Movie value) {
        if (movieBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMovieIsMutable();
          movie_.add(index, value);
          onChanged();
        } else {
          movieBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .proto.Movie movie = 1;</code>
       */
      public Builder addMovie(
          com.example.proto.MovieProtos.Movie.Builder builderForValue) {
        if (movieBuilder_ == null) {
          ensureMovieIsMutable();
          movie_.add(builderForValue.build());
          onChanged();
        } else {
          movieBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto.Movie movie = 1;</code>
       */
      public Builder addMovie(
          int index, com.example.proto.MovieProtos.Movie.Builder builderForValue) {
        if (movieBuilder_ == null) {
          ensureMovieIsMutable();
          movie_.add(index, builderForValue.build());
          onChanged();
        } else {
          movieBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto.Movie movie = 1;</code>
       */
      public Builder addAllMovie(
          java.lang.Iterable<? extends com.example.proto.MovieProtos.Movie> values) {
        if (movieBuilder_ == null) {
          ensureMovieIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, movie_);
          onChanged();
        } else {
          movieBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .proto.Movie movie = 1;</code>
       */
      public Builder clearMovie() {
        if (movieBuilder_ == null) {
          movie_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          movieBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .proto.Movie movie = 1;</code>
       */
      public Builder removeMovie(int index) {
        if (movieBuilder_ == null) {
          ensureMovieIsMutable();
          movie_.remove(index);
          onChanged();
        } else {
          movieBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .proto.Movie movie = 1;</code>
       */
      public com.example.proto.MovieProtos.Movie.Builder getMovieBuilder(
          int index) {
        return getMovieFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .proto.Movie movie = 1;</code>
       */
      public com.example.proto.MovieProtos.MovieOrBuilder getMovieOrBuilder(
          int index) {
        if (movieBuilder_ == null) {
          return movie_.get(index);  } else {
          return movieBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .proto.Movie movie = 1;</code>
       */
      public java.util.List<? extends com.example.proto.MovieProtos.MovieOrBuilder> 
           getMovieOrBuilderList() {
        if (movieBuilder_ != null) {
          return movieBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(movie_);
        }
      }
      /**
       * <code>repeated .proto.Movie movie = 1;</code>
       */
      public com.example.proto.MovieProtos.Movie.Builder addMovieBuilder() {
        return getMovieFieldBuilder().addBuilder(
            com.example.proto.MovieProtos.Movie.getDefaultInstance());
      }
      /**
       * <code>repeated .proto.Movie movie = 1;</code>
       */
      public com.example.proto.MovieProtos.Movie.Builder addMovieBuilder(
          int index) {
        return getMovieFieldBuilder().addBuilder(
            index, com.example.proto.MovieProtos.Movie.getDefaultInstance());
      }
      /**
       * <code>repeated .proto.Movie movie = 1;</code>
       */
      public java.util.List<com.example.proto.MovieProtos.Movie.Builder> 
           getMovieBuilderList() {
        return getMovieFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.example.proto.MovieProtos.Movie, com.example.proto.MovieProtos.Movie.Builder, com.example.proto.MovieProtos.MovieOrBuilder> 
          getMovieFieldBuilder() {
        if (movieBuilder_ == null) {
          movieBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.example.proto.MovieProtos.Movie, com.example.proto.MovieProtos.Movie.Builder, com.example.proto.MovieProtos.MovieOrBuilder>(
                  movie_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          movie_ = null;
        }
        return movieBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:proto.MovieList)
    }

    // @@protoc_insertion_point(class_scope:proto.MovieList)
    private static final com.example.proto.MovieProtos.MovieList DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.example.proto.MovieProtos.MovieList();
    }

    public static com.example.proto.MovieProtos.MovieList getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<MovieList>
        PARSER = new com.google.protobuf.AbstractParser<MovieList>() {
      public MovieList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new MovieList(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MovieList> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MovieList> getParserForType() {
      return PARSER;
    }

    public com.example.proto.MovieProtos.MovieList getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_Movie_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_Movie_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_MovieList_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_MovieList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013movie.proto\022\005proto\"G\n\005Movie\022\n\n\002id\030\001 \002(" +
      "\t\022\017\n\007movieId\030\002 \001(\004\022\014\n\004name\030\003 \001(\t\022\023\n\013crea" +
      "tedDate\030\004 \001(\t\"(\n\tMovieList\022\033\n\005movie\030\001 \003(" +
      "\0132\014.proto.MovieB \n\021com.example.protoB\013Mo" +
      "vieProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_proto_Movie_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_Movie_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_Movie_descriptor,
        new java.lang.String[] { "Id", "MovieId", "Name", "CreatedDate", });
    internal_static_proto_MovieList_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_proto_MovieList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_MovieList_descriptor,
        new java.lang.String[] { "Movie", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
