// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: recc_data.proto

package com.example.proto;

public final class ReccomendationDataProtos {
  private ReccomendationDataProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ReccomendationDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.ReccomendationData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>optional int32 id = 1;</code>
     */
    int getId();

    /**
     * <code>optional int32 likes = 2;</code>
     */
    boolean hasLikes();
    /**
     * <code>optional int32 likes = 2;</code>
     */
    int getLikes();
  }
  /**
   * Protobuf type {@code proto.ReccomendationData}
   */
  public  static final class ReccomendationData extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.ReccomendationData)
      ReccomendationDataOrBuilder {
    // Use ReccomendationData.newBuilder() to construct.
    private ReccomendationData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ReccomendationData() {
      id_ = 0;
      likes_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ReccomendationData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              likes_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.proto.ReccomendationDataProtos.internal_static_proto_ReccomendationData_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.proto.ReccomendationDataProtos.internal_static_proto_ReccomendationData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.proto.ReccomendationDataProtos.ReccomendationData.class, com.example.proto.ReccomendationDataProtos.ReccomendationData.Builder.class);
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>optional int32 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int LIKES_FIELD_NUMBER = 2;
    private int likes_;
    /**
     * <code>optional int32 likes = 2;</code>
     */
    public boolean hasLikes() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 likes = 2;</code>
     */
    public int getLikes() {
      return likes_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, likes_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, likes_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.example.proto.ReccomendationDataProtos.ReccomendationData)) {
        return super.equals(obj);
      }
      com.example.proto.ReccomendationDataProtos.ReccomendationData other = (com.example.proto.ReccomendationDataProtos.ReccomendationData) obj;

      boolean result = true;
      result = result && (hasId() == other.hasId());
      if (hasId()) {
        result = result && (getId()
            == other.getId());
      }
      result = result && (hasLikes() == other.hasLikes());
      if (hasLikes()) {
        result = result && (getLikes()
            == other.getLikes());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasId()) {
        hash = (37 * hash) + ID_FIELD_NUMBER;
        hash = (53 * hash) + getId();
      }
      if (hasLikes()) {
        hash = (37 * hash) + LIKES_FIELD_NUMBER;
        hash = (53 * hash) + getLikes();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.example.proto.ReccomendationDataProtos.ReccomendationData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.proto.ReccomendationDataProtos.ReccomendationData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.proto.ReccomendationDataProtos.ReccomendationData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.proto.ReccomendationDataProtos.ReccomendationData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.proto.ReccomendationDataProtos.ReccomendationData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.proto.ReccomendationDataProtos.ReccomendationData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.proto.ReccomendationDataProtos.ReccomendationData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.example.proto.ReccomendationDataProtos.ReccomendationData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.proto.ReccomendationDataProtos.ReccomendationData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.proto.ReccomendationDataProtos.ReccomendationData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.example.proto.ReccomendationDataProtos.ReccomendationData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.ReccomendationData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.ReccomendationData)
        com.example.proto.ReccomendationDataProtos.ReccomendationDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.example.proto.ReccomendationDataProtos.internal_static_proto_ReccomendationData_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.example.proto.ReccomendationDataProtos.internal_static_proto_ReccomendationData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.example.proto.ReccomendationDataProtos.ReccomendationData.class, com.example.proto.ReccomendationDataProtos.ReccomendationData.Builder.class);
      }

      // Construct using com.example.proto.ReccomendationDataProtos.ReccomendationData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        likes_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.example.proto.ReccomendationDataProtos.internal_static_proto_ReccomendationData_descriptor;
      }

      public com.example.proto.ReccomendationDataProtos.ReccomendationData getDefaultInstanceForType() {
        return com.example.proto.ReccomendationDataProtos.ReccomendationData.getDefaultInstance();
      }

      public com.example.proto.ReccomendationDataProtos.ReccomendationData build() {
        com.example.proto.ReccomendationDataProtos.ReccomendationData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.example.proto.ReccomendationDataProtos.ReccomendationData buildPartial() {
        com.example.proto.ReccomendationDataProtos.ReccomendationData result = new com.example.proto.ReccomendationDataProtos.ReccomendationData(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.likes_ = likes_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.example.proto.ReccomendationDataProtos.ReccomendationData) {
          return mergeFrom((com.example.proto.ReccomendationDataProtos.ReccomendationData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.example.proto.ReccomendationDataProtos.ReccomendationData other) {
        if (other == com.example.proto.ReccomendationDataProtos.ReccomendationData.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasLikes()) {
          setLikes(other.getLikes());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.example.proto.ReccomendationDataProtos.ReccomendationData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.example.proto.ReccomendationDataProtos.ReccomendationData) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <code>optional int32 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>optional int32 id = 1;</code>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      private int likes_ ;
      /**
       * <code>optional int32 likes = 2;</code>
       */
      public boolean hasLikes() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 likes = 2;</code>
       */
      public int getLikes() {
        return likes_;
      }
      /**
       * <code>optional int32 likes = 2;</code>
       */
      public Builder setLikes(int value) {
        bitField0_ |= 0x00000002;
        likes_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 likes = 2;</code>
       */
      public Builder clearLikes() {
        bitField0_ = (bitField0_ & ~0x00000002);
        likes_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:proto.ReccomendationData)
    }

    // @@protoc_insertion_point(class_scope:proto.ReccomendationData)
    private static final com.example.proto.ReccomendationDataProtos.ReccomendationData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.example.proto.ReccomendationDataProtos.ReccomendationData();
    }

    public static com.example.proto.ReccomendationDataProtos.ReccomendationData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<ReccomendationData>
        PARSER = new com.google.protobuf.AbstractParser<ReccomendationData>() {
      public ReccomendationData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ReccomendationData(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ReccomendationData> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ReccomendationData> getParserForType() {
      return PARSER;
    }

    public com.example.proto.ReccomendationDataProtos.ReccomendationData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ReccomendationDataListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.ReccomendationDataList)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .proto.ReccomendationData data = 1;</code>
     */
    java.util.List<com.example.proto.ReccomendationDataProtos.ReccomendationData> 
        getDataList();
    /**
     * <code>repeated .proto.ReccomendationData data = 1;</code>
     */
    com.example.proto.ReccomendationDataProtos.ReccomendationData getData(int index);
    /**
     * <code>repeated .proto.ReccomendationData data = 1;</code>
     */
    int getDataCount();
    /**
     * <code>repeated .proto.ReccomendationData data = 1;</code>
     */
    java.util.List<? extends com.example.proto.ReccomendationDataProtos.ReccomendationDataOrBuilder> 
        getDataOrBuilderList();
    /**
     * <code>repeated .proto.ReccomendationData data = 1;</code>
     */
    com.example.proto.ReccomendationDataProtos.ReccomendationDataOrBuilder getDataOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code proto.ReccomendationDataList}
   */
  public  static final class ReccomendationDataList extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.ReccomendationDataList)
      ReccomendationDataListOrBuilder {
    // Use ReccomendationDataList.newBuilder() to construct.
    private ReccomendationDataList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ReccomendationDataList() {
      data_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ReccomendationDataList(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                data_ = new java.util.ArrayList<com.example.proto.ReccomendationDataProtos.ReccomendationData>();
                mutable_bitField0_ |= 0x00000001;
              }
              data_.add(
                  input.readMessage(com.example.proto.ReccomendationDataProtos.ReccomendationData.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          data_ = java.util.Collections.unmodifiableList(data_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.proto.ReccomendationDataProtos.internal_static_proto_ReccomendationDataList_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.proto.ReccomendationDataProtos.internal_static_proto_ReccomendationDataList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.proto.ReccomendationDataProtos.ReccomendationDataList.class, com.example.proto.ReccomendationDataProtos.ReccomendationDataList.Builder.class);
    }

    public static final int DATA_FIELD_NUMBER = 1;
    private java.util.List<com.example.proto.ReccomendationDataProtos.ReccomendationData> data_;
    /**
     * <code>repeated .proto.ReccomendationData data = 1;</code>
     */
    public java.util.List<com.example.proto.ReccomendationDataProtos.ReccomendationData> getDataList() {
      return data_;
    }
    /**
     * <code>repeated .proto.ReccomendationData data = 1;</code>
     */
    public java.util.List<? extends com.example.proto.ReccomendationDataProtos.ReccomendationDataOrBuilder> 
        getDataOrBuilderList() {
      return data_;
    }
    /**
     * <code>repeated .proto.ReccomendationData data = 1;</code>
     */
    public int getDataCount() {
      return data_.size();
    }
    /**
     * <code>repeated .proto.ReccomendationData data = 1;</code>
     */
    public com.example.proto.ReccomendationDataProtos.ReccomendationData getData(int index) {
      return data_.get(index);
    }
    /**
     * <code>repeated .proto.ReccomendationData data = 1;</code>
     */
    public com.example.proto.ReccomendationDataProtos.ReccomendationDataOrBuilder getDataOrBuilder(
        int index) {
      return data_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < data_.size(); i++) {
        output.writeMessage(1, data_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < data_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, data_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.example.proto.ReccomendationDataProtos.ReccomendationDataList)) {
        return super.equals(obj);
      }
      com.example.proto.ReccomendationDataProtos.ReccomendationDataList other = (com.example.proto.ReccomendationDataProtos.ReccomendationDataList) obj;

      boolean result = true;
      result = result && getDataList()
          .equals(other.getDataList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (getDataCount() > 0) {
        hash = (37 * hash) + DATA_FIELD_NUMBER;
        hash = (53 * hash) + getDataList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.example.proto.ReccomendationDataProtos.ReccomendationDataList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.proto.ReccomendationDataProtos.ReccomendationDataList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.proto.ReccomendationDataProtos.ReccomendationDataList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.proto.ReccomendationDataProtos.ReccomendationDataList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.proto.ReccomendationDataProtos.ReccomendationDataList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.proto.ReccomendationDataProtos.ReccomendationDataList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.proto.ReccomendationDataProtos.ReccomendationDataList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.example.proto.ReccomendationDataProtos.ReccomendationDataList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.proto.ReccomendationDataProtos.ReccomendationDataList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.proto.ReccomendationDataProtos.ReccomendationDataList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.example.proto.ReccomendationDataProtos.ReccomendationDataList prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.ReccomendationDataList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.ReccomendationDataList)
        com.example.proto.ReccomendationDataProtos.ReccomendationDataListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.example.proto.ReccomendationDataProtos.internal_static_proto_ReccomendationDataList_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.example.proto.ReccomendationDataProtos.internal_static_proto_ReccomendationDataList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.example.proto.ReccomendationDataProtos.ReccomendationDataList.class, com.example.proto.ReccomendationDataProtos.ReccomendationDataList.Builder.class);
      }

      // Construct using com.example.proto.ReccomendationDataProtos.ReccomendationDataList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getDataFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (dataBuilder_ == null) {
          data_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          dataBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.example.proto.ReccomendationDataProtos.internal_static_proto_ReccomendationDataList_descriptor;
      }

      public com.example.proto.ReccomendationDataProtos.ReccomendationDataList getDefaultInstanceForType() {
        return com.example.proto.ReccomendationDataProtos.ReccomendationDataList.getDefaultInstance();
      }

      public com.example.proto.ReccomendationDataProtos.ReccomendationDataList build() {
        com.example.proto.ReccomendationDataProtos.ReccomendationDataList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.example.proto.ReccomendationDataProtos.ReccomendationDataList buildPartial() {
        com.example.proto.ReccomendationDataProtos.ReccomendationDataList result = new com.example.proto.ReccomendationDataProtos.ReccomendationDataList(this);
        int from_bitField0_ = bitField0_;
        if (dataBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            data_ = java.util.Collections.unmodifiableList(data_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.data_ = data_;
        } else {
          result.data_ = dataBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.example.proto.ReccomendationDataProtos.ReccomendationDataList) {
          return mergeFrom((com.example.proto.ReccomendationDataProtos.ReccomendationDataList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.example.proto.ReccomendationDataProtos.ReccomendationDataList other) {
        if (other == com.example.proto.ReccomendationDataProtos.ReccomendationDataList.getDefaultInstance()) return this;
        if (dataBuilder_ == null) {
          if (!other.data_.isEmpty()) {
            if (data_.isEmpty()) {
              data_ = other.data_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureDataIsMutable();
              data_.addAll(other.data_);
            }
            onChanged();
          }
        } else {
          if (!other.data_.isEmpty()) {
            if (dataBuilder_.isEmpty()) {
              dataBuilder_.dispose();
              dataBuilder_ = null;
              data_ = other.data_;
              bitField0_ = (bitField0_ & ~0x00000001);
              dataBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getDataFieldBuilder() : null;
            } else {
              dataBuilder_.addAllMessages(other.data_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.example.proto.ReccomendationDataProtos.ReccomendationDataList parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.example.proto.ReccomendationDataProtos.ReccomendationDataList) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.example.proto.ReccomendationDataProtos.ReccomendationData> data_ =
        java.util.Collections.emptyList();
      private void ensureDataIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          data_ = new java.util.ArrayList<com.example.proto.ReccomendationDataProtos.ReccomendationData>(data_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.example.proto.ReccomendationDataProtos.ReccomendationData, com.example.proto.ReccomendationDataProtos.ReccomendationData.Builder, com.example.proto.ReccomendationDataProtos.ReccomendationDataOrBuilder> dataBuilder_;

      /**
       * <code>repeated .proto.ReccomendationData data = 1;</code>
       */
      public java.util.List<com.example.proto.ReccomendationDataProtos.ReccomendationData> getDataList() {
        if (dataBuilder_ == null) {
          return java.util.Collections.unmodifiableList(data_);
        } else {
          return dataBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .proto.ReccomendationData data = 1;</code>
       */
      public int getDataCount() {
        if (dataBuilder_ == null) {
          return data_.size();
        } else {
          return dataBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .proto.ReccomendationData data = 1;</code>
       */
      public com.example.proto.ReccomendationDataProtos.ReccomendationData getData(int index) {
        if (dataBuilder_ == null) {
          return data_.get(index);
        } else {
          return dataBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .proto.ReccomendationData data = 1;</code>
       */
      public Builder setData(
          int index, com.example.proto.ReccomendationDataProtos.ReccomendationData value) {
        if (dataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDataIsMutable();
          data_.set(index, value);
          onChanged();
        } else {
          dataBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .proto.ReccomendationData data = 1;</code>
       */
      public Builder setData(
          int index, com.example.proto.ReccomendationDataProtos.ReccomendationData.Builder builderForValue) {
        if (dataBuilder_ == null) {
          ensureDataIsMutable();
          data_.set(index, builderForValue.build());
          onChanged();
        } else {
          dataBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto.ReccomendationData data = 1;</code>
       */
      public Builder addData(com.example.proto.ReccomendationDataProtos.ReccomendationData value) {
        if (dataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDataIsMutable();
          data_.add(value);
          onChanged();
        } else {
          dataBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .proto.ReccomendationData data = 1;</code>
       */
      public Builder addData(
          int index, com.example.proto.ReccomendationDataProtos.ReccomendationData value) {
        if (dataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDataIsMutable();
          data_.add(index, value);
          onChanged();
        } else {
          dataBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .proto.ReccomendationData data = 1;</code>
       */
      public Builder addData(
          com.example.proto.ReccomendationDataProtos.ReccomendationData.Builder builderForValue) {
        if (dataBuilder_ == null) {
          ensureDataIsMutable();
          data_.add(builderForValue.build());
          onChanged();
        } else {
          dataBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto.ReccomendationData data = 1;</code>
       */
      public Builder addData(
          int index, com.example.proto.ReccomendationDataProtos.ReccomendationData.Builder builderForValue) {
        if (dataBuilder_ == null) {
          ensureDataIsMutable();
          data_.add(index, builderForValue.build());
          onChanged();
        } else {
          dataBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto.ReccomendationData data = 1;</code>
       */
      public Builder addAllData(
          java.lang.Iterable<? extends com.example.proto.ReccomendationDataProtos.ReccomendationData> values) {
        if (dataBuilder_ == null) {
          ensureDataIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, data_);
          onChanged();
        } else {
          dataBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .proto.ReccomendationData data = 1;</code>
       */
      public Builder clearData() {
        if (dataBuilder_ == null) {
          data_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          dataBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .proto.ReccomendationData data = 1;</code>
       */
      public Builder removeData(int index) {
        if (dataBuilder_ == null) {
          ensureDataIsMutable();
          data_.remove(index);
          onChanged();
        } else {
          dataBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .proto.ReccomendationData data = 1;</code>
       */
      public com.example.proto.ReccomendationDataProtos.ReccomendationData.Builder getDataBuilder(
          int index) {
        return getDataFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .proto.ReccomendationData data = 1;</code>
       */
      public com.example.proto.ReccomendationDataProtos.ReccomendationDataOrBuilder getDataOrBuilder(
          int index) {
        if (dataBuilder_ == null) {
          return data_.get(index);  } else {
          return dataBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .proto.ReccomendationData data = 1;</code>
       */
      public java.util.List<? extends com.example.proto.ReccomendationDataProtos.ReccomendationDataOrBuilder> 
           getDataOrBuilderList() {
        if (dataBuilder_ != null) {
          return dataBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(data_);
        }
      }
      /**
       * <code>repeated .proto.ReccomendationData data = 1;</code>
       */
      public com.example.proto.ReccomendationDataProtos.ReccomendationData.Builder addDataBuilder() {
        return getDataFieldBuilder().addBuilder(
            com.example.proto.ReccomendationDataProtos.ReccomendationData.getDefaultInstance());
      }
      /**
       * <code>repeated .proto.ReccomendationData data = 1;</code>
       */
      public com.example.proto.ReccomendationDataProtos.ReccomendationData.Builder addDataBuilder(
          int index) {
        return getDataFieldBuilder().addBuilder(
            index, com.example.proto.ReccomendationDataProtos.ReccomendationData.getDefaultInstance());
      }
      /**
       * <code>repeated .proto.ReccomendationData data = 1;</code>
       */
      public java.util.List<com.example.proto.ReccomendationDataProtos.ReccomendationData.Builder> 
           getDataBuilderList() {
        return getDataFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.example.proto.ReccomendationDataProtos.ReccomendationData, com.example.proto.ReccomendationDataProtos.ReccomendationData.Builder, com.example.proto.ReccomendationDataProtos.ReccomendationDataOrBuilder> 
          getDataFieldBuilder() {
        if (dataBuilder_ == null) {
          dataBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.example.proto.ReccomendationDataProtos.ReccomendationData, com.example.proto.ReccomendationDataProtos.ReccomendationData.Builder, com.example.proto.ReccomendationDataProtos.ReccomendationDataOrBuilder>(
                  data_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          data_ = null;
        }
        return dataBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:proto.ReccomendationDataList)
    }

    // @@protoc_insertion_point(class_scope:proto.ReccomendationDataList)
    private static final com.example.proto.ReccomendationDataProtos.ReccomendationDataList DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.example.proto.ReccomendationDataProtos.ReccomendationDataList();
    }

    public static com.example.proto.ReccomendationDataProtos.ReccomendationDataList getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<ReccomendationDataList>
        PARSER = new com.google.protobuf.AbstractParser<ReccomendationDataList>() {
      public ReccomendationDataList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ReccomendationDataList(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ReccomendationDataList> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ReccomendationDataList> getParserForType() {
      return PARSER;
    }

    public com.example.proto.ReccomendationDataProtos.ReccomendationDataList getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_ReccomendationData_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_ReccomendationData_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_ReccomendationDataList_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_ReccomendationDataList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017recc_data.proto\022\005proto\"/\n\022Reccomendati" +
      "onData\022\n\n\002id\030\001 \001(\005\022\r\n\005likes\030\002 \001(\005\"A\n\026Rec" +
      "comendationDataList\022\'\n\004data\030\001 \003(\0132\031.prot" +
      "o.ReccomendationDataB-\n\021com.example.prot" +
      "oB\030ReccomendationDataProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_proto_ReccomendationData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_ReccomendationData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_ReccomendationData_descriptor,
        new java.lang.String[] { "Id", "Likes", });
    internal_static_proto_ReccomendationDataList_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_proto_ReccomendationDataList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_ReccomendationDataList_descriptor,
        new java.lang.String[] { "Data", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
